### ISSUE TITLE
K4G41325FE memory not recognized

### ISSUE THREAD

**Issue by tacchinotacchi** [jaschaknack/PolarisBiosEditor#10]
On a Sapphire rx 470 nitro non plus 4 gb ( the reference design one ). Should I provide some timings? How does this work?

**Comment by jaschaknack** [comment]
If you could provide me an original bios file and/or pretested good working timings / a mod bios, I would integrate memory support for 4g samsung into the program.

**Comment by cyeedar** [comment]
Dear Jascha,

I'm facing the same problem but the VRAM code is K4G41325FC (UNKNOWN) instead.
Attached is the original BIOS I hope you can help, thanks a lot for your great app!

[RX470_4G_mining_samsung.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1309070/RX470_4G_mining_samsung.zip)

**Comment by jaschaknack** [comment]
I implemented support for both 4G SAMSUNG timings (version 1.6.2). Please test and report.

**Comment by jaschaknack** [comment]
@cyeedar Did you have any success?

**Comment by cyeedar** [comment]
@jaschaknack Sorry for late reply, yes it works. However, performance of K4G41325FC is terrible, max OC of memory is around 1900-1950 only before incorrect shares start appearing.

**Comment by cyeedar** [comment]
Dear Jascha,

I hope you can take a look at this timings if you don't mind. It is from the latest MSI RX570 4G gaming card with Elpida memory EDW4032BAB.

Your editor can detect the memory and fill the timings, but it doesn't seem to work. This card can run at 2030 memory OC at stock ROM, however once flashed ROM it will crash within 1-2 mins of mining.

The weird thing is EDW4032BAB is exactly same as some Sapphire RX470 4G cards that I own and your timings work perfectly fine on them. 

Again, thank you for your hard work lemme know if you take any donations!
[test.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1419504/test.zip)

**Comment by jaschaknack** [comment]
Can you see the print on the memory chips? Maybe they are different but already factory overclocked?

**Comment by cyeedar** [comment]
I don't think they are factory overclocked as stock ROM running at 2000 memory (stable) only yields around 25Mh/s

**Comment by jaschaknack** [comment]
Please have a look here:

https://tpucdn.com/reviews/Zotac/GeForce_GTX_1060_Mini_3_GB/images/memory_small.jpg

Can you verify that both cards have the same memory chips? Are there any differences?

**Comment by jaschaknack** [comment]
@tacchinotacchi @cyeedar Is this still open?

**Comment by thanhtoan17** [comment]
[The Msi 470 mining 4g Samsung.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1544915/The.Msi.470.mining.4g.Samsung.zip)
I mod that bios by PolarisBiosEditor 1.6.4 by clịck timing path, and it's not run on my Vga, can you help me

**Comment by jaschaknack** [comment]
closing this for now, @thanhtoan17 we solve your problem in the other thread!
