### ISSUE TITLE
Support for H5GQ8H24MJR

### ISSUE THREAD

**Issue by mladenperisic** [jaschaknack/PolarisBiosEditor#11]
Hello, can you please add support for Hynix H5GQ8H24MJR? I don't have good timings, but I can provide you with atm latest unmodified BIOS for Gigabyte GV-RX580XTRAORUS-8GD. Thank you very much for this great app!
[GV-RX580XTRAORUS-8GD-F10-058C.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1290014/GV-RX580XTRAORUS-8GD-F10-058C.zip)

**Comment by jaschaknack** [comment]
Hi, support for this memory is already implemented. Please use the latest version, as of today is 1.6.1. Best Regards
