### ISSUE TITLE
sorry, no supported memory found

### ISSUE THREAD

**Issue by philejmath** [jaschaknack/PolarisBiosEditor#12]
MSI Armor Radeon RX470 8 GB 

I get the message "sorry, no supported memory found" when I click the one click timing patch button.  

Just curious if this is really unsupported or if something else is up.

**Comment by jaschaknack** [comment]
Hi,
please attach the bios rom so I can have a look at it.

**Comment by philejmath** [comment]
Hello, 
how do I download bios rom on ubuntu ?

**Comment by philejmath** [comment]
I searched google and it's not entirely evident. If you have any resources/links to these instructions it would be greatly appreciated.

**Comment by jaschaknack** [comment]
There is an atiflash linux version out there but I had no luck finding it. But how did you get the error message without a rom from your gpu?

**Comment by philejmath** [comment]
by opening the editor and clicking the "one click patch" button. I guess I need the rom file to edit in the bios editor though. sorry, new at this... 

I can find windows a version of windows to boot to and download the rom. 

-phil

**Comment by jaschaknack** [comment]
Yes, you need the rom from your gpu to edit the timings. Please have a look here: https://anorak.tech/t/how-to-flash-a-amd-graphic-card-vbios/15
