### ISSUE TITLE
RX 570 Gigabyte Gaming 4G 

### ISSUE THREAD

**Issue by karep** [jaschaknack/PolarisBiosEditor#13]
There is no 2000+ on this gpu. 

[rx570gigabyte_4g_hynix.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1308748/rx570gigabyte_4g_hynix.zip)
[https://www.gigabyte.com/Graphics-Card/GV-RX570GAMING-4GD#support-dl](url)

**Comment by jaschaknack** [comment]
Fixed (version 1.6.2). Now timings are applied at 1750+. Please test and report.

**Comment by karep** [comment]
Thanks for fast respons to update v1.6.2
But for this type GPU I'have only get 26+Mhs
For comparison, other brand with same type, I got 30+Mhs
Maybe need "special" timings code to get max hasrate on this GPU.
Anyway thanks for all your hardworked.

**Comment by jaschaknack** [comment]
Did you still overclock your memory after the timing patch? If you can provide a bios with better timings, I would be happy to integrate them.
