### ISSUE TITLE
Gigabyte RX580 Gaming 8GB

### ISSUE THREAD

**Issue by whysthatso** [jaschaknack/PolarisBiosEditor#14]
Hey,
seems that the editor only recognizes timings until 1500 for this bios. I've attached the original rom.

Also discussed here:
https://bitcointalk.org/index.php?topic=2196941.msg22163951
and here:
https://www.reddit.com/r/EtherMining/comments/70ff91/gigabyte_rx_580_8bg_memory_timings_only_showing/

let me know if i can help with this somehow.

[gb.bios.org.rom.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1327890/gb.bios.org.rom.zip)

**Comment by jaschaknack** [comment]
Hi,

you could try the following timings:
777000000000000022AA1C00B56A6D46C0551017BE8E060C006AE6000C081420EA8900AB030000001B162C31C0313F17

Just put them into the 1500 box and crank up the maximum vram frequency in the powerplay section. Then you have to overclock your vram with e.g. Afterburner.

Please let me know your results before & after.

**Comment by whysthatso** [comment]
i  set rx580 cards usually at:
mem: 2100/850mv
gpu: 1100/850mv
i had not adjusted the timings then.

as a starting point, this produced only false shares with claymore at 25Mhashes/sec

following your suggestion, i've put this into the 1500: box,
i've also set:
mem: 2050/850
gpu: 1100/850

now hashrate is unchanged at 25, but no more errors. on a good point, the card only draws ~100 watt.

however, i think the new timing strap does not yet do anything

i.e. other rx850 i set on the 2100/1100 combination with 850mv and 1500 straps applied to 2000, they usually also fall to 100 watt, and bring ~29 hashes, which is the sweet spot for me.

**Comment by whysthatso** [comment]
sorry if i get the vocabulary not perfectly right, i assume:
1500 strap = timing

**Comment by rx3r** [comment]
Hi. Please read this. https://anorak.tech/t/gigabyte-rx-580-gaming-8gb-has-only-1500-timings-now/26757

on old cards version if u change higher timings with ...3F17 u get higher hasrate if use 1150 2150 950

on new cards released this month they don't have  +1750 timings, stops at 1500.

apply modded bios that has 1750 and if u go with memory over 2000 you get errors depending.

2100 - error after 1 hour
2150 - 50 errors per minute, less, or more.

card is sensitive to cooling. if u go with fan 100% i see less errors.

also at my first tests i had august 11 betachain driver. many errors.

i reinstalled 23 august driver and removed wattman, only have driver. less errors at 2150. and here i noted if fan is 100% less errors. still errors.

option is to use 1150 2100 950 with highest hasrate/error  - 29.6 with 1 error an hour.

 1150 2000 950   28mh with no errrors

1150 2150 950 30,3 mhs with many errors.

----

anyone managed to add any timings and over +2000 with no errors after 1 hour and +30mhs ?

**Comment by rx3r** [comment]
whysthatso, use the setting from jaschaknack and try 1150 2150 950 ... how many errors u get ?

**Comment by rx3r** [comment]
777000000000000022AA1C00B56A6D46C0551017BE8E060C006AE6000C081420EA8900AB030000001B162C31C0313F17 in 1500 timing and 900mv 900 mv - 25.8 mhs default.

1150 2150 900mv 900 mv - 27.4

using old version bios and add in 1750 timings the ... 3F17  you get 1150 2150 900mv 900 mv  but with errors. while old card version in this settings is no error.

buy new gigabyte if you want a max 29.6 with no errors (or maybe 1-2 error from time to time).  1500 modded with 1150 2000 is 28mhs.  i ended my tests. tried many settings for a week. maybe others can get to 30 with no errors... i didn't.

**Comment by rx3r** [comment]
whysthatso, any update ?

**Comment by whysthatso** [comment]
i haven't found the time yet, but i'm still on it.

**Comment by michaeljohnbennett** [comment]
https://anorak.tech/t/gigabyte-rx-580-gaming-8gb-has-only-1500-timings-now/26757/81 

There is a full discussion here on the bios mod to get the higher timings back. It's not a problem with the BiosEditor. Gigabyte hamstrung the latest bios.

**Comment by whysthatso** [comment]
well, it's really hard to say. @rx3r i've tried your last timeings but only one of four cards was stable on long term. i could also only get them as high as ~25MHashes.
so to be honest, i'm just not considering them for the future and give up, probably sell those off.

**Comment by rx3r** [comment]
Quote bitcoin talk: "Using umr I see pretty much post 1500 timings(2000 actually) realtime. There are hidden timings in command tables"

For this card I applyed old bios version and new timings, and is stable, don't know why is not for you.

29.1 no errors, or 29.6 errors 1 an hour.

See: https://imgur.com/a/VWqEv
