### ISSUE TITLE
Unsupported DeviceID 0x67FF

### ISSUE THREAD

**Issue by nthwave** [jaschaknack/PolarisBiosEditor#15]
Getting this error when attempting to open file: Unsupported DeviceID 0x67FF

Sapphire Pulse Radeon RX560 4Gb - OC edition
H5GC8H24MJ (Hynix_2)

Wondering if its me  - attached file to assist. Just rename .txt to .rom 

[Baffin_Original_Rom.txt](https://github.com/jaschaknack/PolarisBiosEditor/files/1402023/Baffin_Original_Rom.txt)
![gpu-z](https://user-images.githubusercontent.com/20896213/31822840-ac322930-b56f-11e7-96c3-a3431208ef3e.gif)

**Comment by jaschaknack** [comment]
Please try version 1.6.3

**Comment by nthwave** [comment]
Thanks you very much. So far no errors with this version - your skills are much appreciated.
