### ISSUE TITLE
H5GC8H24MJ not showing straps over 0:1500 

### ISSUE THREAD

**Issue by v-vayer** [jaschaknack/PolarisBiosEditor#16]
Using v1.6.2. - unable to update straps above 1500 because they are not visible. One click patch suggests good timings, but does nothing. Original ROM and a screenshot attached.

![issue](https://user-images.githubusercontent.com/4146391/31866381-5895ecde-b787-11e7-93f6-c6481190c4d8.png)

[aorus-rx580-8g-original.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1405342/aorus-rx580-8g-original.zip)

**Comment by jaschaknack** [comment]
This seems to be an issue for several newer cards. I could alter the patch function to operate on all timings that are 1500 (inclusive) and above. Would that work for you?

**Comment by jaschaknack** [comment]
Please try version 1.6.3

**Comment by v-vayer** [comment]
Thanks, Jascha! I can see that 1500 gets updated, but no straps beyond 1500 appearing after the patch. Is this what you meant? Is this a correct solution in terms of performance?

**Comment by jaschaknack** [comment]
Please give it a try!

**Comment by v-vayer** [comment]
I confirm that it's working correctly and giving the expected hash rate 👍
