### ISSUE TITLE
No supported memory found

### ISSUE THREAD

**Issue by Kastor83** [jaschaknack/PolarisBiosEditor#17]
XFX RX-580 only hashes at 20Mh/s stock.  WattMan adjustments only lower hashrate.  Full model number is RX-580P8DBRR.  GPU-Z tells me this card uses Hynix memory.

Tried PolarisBiosEditor, received error "Sorry, no supported memory found."

I saw you asked someone else for their stock bios, I am new to this, how would I save a copy in order to provide it?

**Comment by Kastor83** [comment]
I found my issue.

I thought the tool modified the current bios in-place.  I saved the bios, modded and flashed to card.  580 is now hashing at 24.5Mh/s stock.  Not great but it's an improvement.

Thank you for making your tool available to noobs like myself, it is appreciated!

**Comment by jaschaknack** [comment]
And now try also:
1) This driver, designed for mining workloads: http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx
2) Downclock your GPU to 1100 and try to overclock your memory...

**Comment by Kastor83** [comment]
Thanks for the suggestion.  

I tried that driver when it was released, and again today.  If a clean install completes without errors (50% chance), Claymore crashes immediately.  Tried install multiple times on a modern AM4 system with Vega cards, as well as older AM2/AM3 systems with 390/580 cards with the same results.

Tried memory only overclock on 580 from 2000 to 2150, hash rate went up from 24.5 to 26.2.  Clocked core down to 1100 and memory up to 2200, hash rate went down to around 24.2.  Though obviously using less power.  Looks like 26 is about the best I can get out of this card.

Thanks again for your help.

**Comment by jaschaknack** [comment]
It sounds that too much OC gives you (correctable) memory errors. You can check them with HWiNFO. Regarding your hashrate issue, you really need to get the blockchain driver up. It speeds things really up, in my case from 25 to 31. I didn't tried with vega but on rx560, rx480 and r9 390 the driver works like a charm.
