### ISSUE TITLE
k4g41325fs not supported

### ISSUE THREAD

**Issue by marcipan73** [jaschaknack/PolarisBiosEditor#18]
hi 
Sapphire nitro 4G RX470 mining edition not support?

[RX470mining4G_oreg.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1482466/RX470mining4G_oreg.zip)

**Comment by marcipan73** [comment]
I add this line to source and compiled.

  rc.Add("K4G41325FS", "SAMSUNG");

working :)

**Comment by jaschaknack** [comment]
Thank you for your contribution. Will add this one. Maybe you can test the Ubermix 3.2 timings as stated in issue #19 ? Would be helpful and maybe also worth it for you :)

**Comment by jaschaknack** [comment]
v1.6.4 is out
