### ISSUE TITLE
Strap adjustments: Elpida strap is incorrect, Samsung UberMix 3.2

### ISSUE THREAD

**Issue by nitrobg** [jaschaknack/PolarisBiosEditor#19]
The correct Elpida strap is:
`777000000000000022AA1C00315A5B36A0550F15B68C1506004082007C041420CA8980A9020004C01712262B612B3715`
Source: https://bitcointalk.org/index.php?topic=2163949.msg21903544#msg21903544

Samsung UberMix 3.2 exists but needs testing:
`777000000000000022CC1C00CEE55C46C0590E1532CD66090060070014051420FA8900A00300000012123442C3353C19`
Source: http://www.overclock.net/t/1604567/polaris-bios-editing-rx5xx-rx4xx/3030#post_26091743

**Comment by jaschaknack** [comment]
Thank you for your contribution. Will fix the Elpida one, maybe someone can test the Samsung timings or post reviews from another source?

**Comment by jaschaknack** [comment]
v1.6.4 is out
