### ISSUE TITLE
Error When Opening Rom - ASUS RX570

### ISSUE THREAD

**Issue by gh0stshell** [jaschaknack/PolarisBiosEditor#20]
![image](https://user-images.githubusercontent.com/1724215/33450796-32b01e48-d5ca-11e7-9898-0af4ee98454d.png)

Happens when I open the ROM, program seems to open fine. Windows 7 Pro.

**Comment by jaschaknack** [comment]
Please make sure you have .NET Framework 3.5 installed.

**Comment by gh0stshell** [comment]
I did redo the computer so I will check. Trying it on my Win10 computer now

**Comment by gh0stshell** [comment]
Works on my Win10 computer so you are probably right on my Win7 computer, you app is interesting that it sees my card has 2 memory indexs while the old versions show just one
