### ISSUE TITLE
Bios with 3 memory brand cant show up

### ISSUE THREAD

**Issue by trungthanh1288** [jaschaknack/PolarisBiosEditor#22]
![2017-12-02 1](https://user-images.githubusercontent.com/33550841/33517691-3cd9b4f4-d7bb-11e7-84a0-f1e40df03217.png)
This is MSI 570 Gaming 4G Samsung memory, software show Samsung memory at index#3 but it not show up to edit timing. Tried One click timing but no luck

**Comment by Eden-Sun** [comment]
+1

**Comment by thanhtoan17** [comment]
[470goc.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1544738/470goc.zip)
Plz help me mod this bios. This is MSI 470 Mining 4G Samsung memory, software show Samsung memory at index#1 but it's not running when i upload to card.

**Comment by jaschaknack** [comment]
@thanhtoan17 what do you mean by 'not running'? GPU not booting anymore or no effect?

**Comment by jaschaknack** [comment]
Please check v1.6.5 with support for up to 4 memory vendors

**Comment by trungthanh1288** [comment]
Thank jaschacknack. With new update i’ll not have to edit bios timing with hex workshop anymore 😁

**Comment by thanhtoan17** [comment]
@jaschaknack Thanks, i forgot run atikmdag-patcher
