### ISSUE TITLE
Unsupported DeviceID 0x699f

### ISSUE THREAD

**Issue by bowerstech** [jaschaknack/PolarisBiosEditor#24]
Hello,

I used ATIWinFlash 2.77 to extract the BIOS from my AMD RX 550 card.  When I used PBE 1.6.4 to open the saved file I received the error in the title.  Is it safe to proceed as I don't want to brick the video card.

Thanks!

**Comment by jaschaknack** [comment]
Hi,
please attach BIOS rom from our card.
Kind Regards,
Jascha

**Comment by jaschaknack** [comment]
Hi,
please use v1.6.6.
Kind Regards
