### ISSUE TITLE
Editor Now Getting Detected As Trojan

### ISSUE THREAD

**Issue by gh0stshell** [jaschaknack/PolarisBiosEditor#25]
![image](https://user-images.githubusercontent.com/1724215/33849009-96052420-de6c-11e7-8517-599328146413.png)

The original 1.5 editor I have does not get the same result.

**Comment by jaschaknack** [comment]
Hi,
this is a false positive. Please check the binary at virustotal.com or compile the sources yourself.
Kind Regards
