### ISSUE TITLE
Ubuntu 16.04 does not see rx580

### ISSUE THREAD

**Issue by ninjavz** [jaschaknack/PolarisBiosEditor#27]
Hi, compiled and got this:
PolarisBiosEditor.cs(507,28): warning CS0219: The variable `decode' is assigned but its value is never used
PolarisBiosEditor.cs(19,18): warning CS0414: The private field `PolarisBiosEditor.PolarisBiosEditor.manufacturers' is assigned but its value is never used
Compilation succeeded - 2 warning(s)

When running ./run it works but on the screen all values appear empty. I have 2 rx580 installed.
Any suggestions?

**Comment by jaschaknack** [comment]
Hi,
you have to read your bios and open it in the editor with the open button. Then you can make changes and save them back into another file which you flash to the graphics card.
Kind Regards

**Comment by ninjavz** [comment]
Under Linux there's no option to read it. It says OPEN BIOS but when I click on it it shows a window to open a .ROM file. Will try on Windows later just to make sure all is running well in the Linux/Mono version.

**Comment by jaschaknack** [comment]
Erm ok i see your problem let me explain:

This tool is only an editor. You have to read the binary from the bios flash before with another tool, called atiflash. Atiflash gives you then a file which you can open in the PolarisBiosEditor and modify it to your needs. After you modified the file you save it as another file which you can flash back to your bios with atiflash.

Everything clear?

Kind Regards

**Comment by ninjavz** [comment]
Yes! Thank you.
