### ISSUE TITLE
Unsupported Gygabyte RX560 DeviceID 0x67ef

### ISSUE THREAD

**Issue by wwarlock** [jaschaknack/PolarisBiosEditor#30]
Here is the BIOS:
[vbios-0-RadeonRX460-4G--xxx-xxx-xxx.rom.zip](https://github.com/jaschaknack/PolarisBiosEditor/files/1594761/vbios-0-RadeonRX460-4G--xxx-xxx-xxx.rom.zip)

Additional optional question:
Is it possible to rename it to the real name via BIOS?

**Comment by wwarlock** [comment]
I may offer you my pull request, but I'm not sure that adding ID to supported devices array is the complete solution.

**Comment by jaschaknack** [comment]
Your pull request would be appreciated, I'll have a look at this feature request this week then.

**Comment by jaschaknack** [comment]
support is integrated into v1.6.7
