### ISSUE TITLE
App wont start correctly

### ISSUE THREAD

**Issue by gnome73** [jaschaknack/PolarisBiosEditor#6]
Hi there,

I downloaded and extracted to a folder and ran under Win10 64 Bit (also tried run as admin) and it wont load the app properly - I just get a window frame and thats all - see pic below.  Do I need any supporting files?

I tried running the app on another PC and it ran fine.

My machine is a mining rig and win10 64bit is bare bones with windows updates turned off.

![image](https://user-images.githubusercontent.com/30827852/29064897-943abb3c-7c7e-11e7-8012-4f1687dff75f.png)

**Comment by jaschaknack** [comment]
Please check if you have .NET framework 3.5 installed. You can also try a "repair installation".

I would suggest you try this with the latest program version. I updated the program five minutes ago :)

**Comment by jaschaknack** [comment]
Did you had any success?
