### ISSUE TITLE
Does the bios update works for linux and all amd 5xx graphics

### ISSUE THREAD

**Issue by CasaSky** [jaschaknack/PolarisBiosEditor#7]
Hi, i have a question about this bios update before starting it.
I am using linux with **kernel 4.8.0-53**.
My graphic card is **GIGABYTE RX 560 OC 4G**.
I am mining **ethereum** using **claymore** miner.

Does it already works without any issues for someone with the same attributes?

**Comment by jaschaknack** [comment]
This is not a bios update! This is a tool to produce your own modified bios. If you have another GPU (IGP, second GPU) you can unbrick your GPU when needed. Please backup your original BIOS first.
