### ISSUE TITLE
windows defender auto deleted exe as virus

### ISSUE THREAD

**Issue by davethefixer** [jaschaknack/PolarisBiosEditor#8]
Trojan:Win32/Spursint.F!cl

just an observation
windows defender autodeleted the exe file as it downloaded.

**Comment by jaschaknack** [comment]
VirusTotal shows 1/64

https://virustotal.com/#/file/b46d907b7da0ff79f1e5d5c04f0db7573adbe6c8be0eaed2e600ad2dd6713cee/detection

so it's clearly a false positive :)
