### ISSUE TITLE
Gigabyte RX580 Gaming 8G showing as unknown memory

### ISSUE THREAD

**Issue by mascondante** [jaschaknack/PolarisBiosEditor#9]
VRAM shows as **H5GC8H24MJ (UNKNOWN)** yet [as you can see](https://www.dropbox.com/s/ts50qkvrlr731vx/Screenshot%202017-09-05%2000.41.11.png?dl=0) It is Hynix. Any way you could include support for one click timing for the Gigabyte models with Hynix memory?

https://anorak.tech/t/bios-mod-request-for-rx580-gigabyte-aorus-8gb-hynix/7864 may be helpful as it has some example BIOS files of original and modified for the Gigabyte regular and gaming cards.

Thank you.

**Comment by jaschaknack** [comment]
I fixed the issue, see updated version 1.6.1. Thank you for your input.
